### ISSUE TITLE
增加组件的漏洞信息导出的API

### ISSUE THREAD

**Issue by coffeehb** [huoxianclub/LingZhi#4]
可导出存在漏洞的组件信息，包括：组件名，当前使用版本，漏洞名，漏洞等级，CVE编号，安全版本。

**Comment by exexute** [comment]
内部评审优先级后给出预计上线时间

**Comment by exexute** [comment]
评估完成，预计下周在新版本中上线，新版本地址：http://aws.iast.huoxian.cn:8000/login

**Comment by coffeehb** [comment]
nice 啊
